title: MightyElemental
description: My project collection
markdown: kramdown
theme: jekyll-theme-hacker
url: "https://www.mightyelemental.net"
plugins:
  - jekyll-seo-tag
  - jekyll-sass-converter
sass:
  style: compact